"""initial schema

Revision ID: 812d60b909f3
Revises: 
Create Date: 2026-07-23 23:40:33.948356
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.infrastructure.db.models import UTCDateTime


revision: str = '812d60b909f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_rooms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('control_mode', sa.String(length=32), nullable=False),
    sa.Column('target_range', sa.JSON(), nullable=False),
    sa.Column('safety_params', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_rules_rule_code'), ['rule_code'], unique=False)

    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_events_room_id'), ['room_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_room_id'), ['room_id'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('inbound_at', UTCDateTime(), nullable=False),
    sa.Column('maturity', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('recommended_range', sa.JSON(), nullable=False),
    sa.Column('max_storage_hours', sa.Integer(), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_room_id'), ['room_id'], unique=False)

    op.create_table('room_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('at', UTCDateTime(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_events_room_id'), ['room_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_room_id'), ['room_id'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('finished_at', UTCDateTime(), nullable=True),
    sa.Column('agent_mode', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=32), nullable=True),
    sa.Column('knowledge_version', sa.String(length=32), nullable=True),
    sa.Column('tool_registry_version', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_event_id'), ['event_id'], unique=False)

    op.create_table('control_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('approval_level', sa.String(length=8), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('rollback_conditions', sa.JSON(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_plans_event_id'), ['event_id'], unique=False)

    op.create_table('event_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('generated_at', UTCDateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('cause_summary', sa.JSON(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('approval', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_reports_event_id'), ['event_id'], unique=True)

    op.create_table('security_audit_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('attempted_at', UTCDateTime(), nullable=False),
    sa.Column('approval_level', sa.String(length=8), nullable=False),
    sa.Column('triggered_rule', sa.String(length=128), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('entry_hash', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_number')
    )
    with op.batch_alter_table('security_audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_audit_entries_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_entries_event_id'), ['event_id'], unique=False)

    op.create_table('telemetry_series',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sample_at', UTCDateTime(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['cold_rooms.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_series_room_id'), ['room_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('safety_checks', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', UTCDateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_plan_id'), ['plan_id'], unique=False)

    op.create_table('control_plan_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version', name='uq_plan_version')
    )
    with op.batch_alter_table('control_plan_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_plan_versions_plan_id'), ['plan_id'], unique=False)

    op.create_table('diagnosis_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('understanding', sa.Text(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['anomaly_events.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_results_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_results_task_id'), ['task_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('finished_at', UTCDateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_plan_id'), ['plan_id'], unique=False)

    op.create_table('tool_invocations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('redaction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_invocations_task_id'), ['task_id'], unique=False)

    op.create_table('control_commands',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'plan_version', 'approval_request_id', name='uq_command_plan_version_approval')
    )
    with op.batch_alter_table('control_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_commands_approval_request_id'), ['approval_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_commands_plan_id'), ['plan_id'], unique=False)

    op.create_table('diagnostic_causes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('triage_order', sa.Integer(), nullable=False),
    sa.Column('recommended_checks', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_causes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_causes_diagnosis_id'), ['diagnosis_id'], unique=False)

    op.create_table('simulation_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('recovery_hours', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('overshoot_risk', sa.String(length=16), nullable=False),
    sa.Column('frost_risk', sa.String(length=16), nullable=False),
    sa.Column('compressor_cycles', sa.Integer(), nullable=False),
    sa.Column('predicted_series', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'plan_version', name='uq_sim_plan_version')
    )
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_results_plan_id'), ['plan_id'], unique=False)

    op.create_table('diagnostic_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cause_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['cause_id'], ['diagnostic_causes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_evidence_cause_id'), ['cause_id'], unique=False)

    op.create_table('execution_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('finished_at', UTCDateTime(), nullable=True),
    sa.Column('recovery_minutes', sa.Integer(), nullable=True),
    sa.Column('triggered_rollback', sa.Text(), nullable=True),
    sa.Column('observed_series', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('last_advanced_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['control_commands.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['control_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_tasks_approval_request_id'), ['approval_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_tasks_command_id'), ['command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('verification_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_task_id', sa.String(length=64), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('decided_at', UTCDateTime(), nullable=False),
    sa.Column('observed_tail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execution_task_id'], ['execution_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_execution_task_id'), ['execution_task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_execution_task_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('execution_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_tasks_plan_id'))
        batch_op.drop_index(batch_op.f('ix_execution_tasks_command_id'))
        batch_op.drop_index(batch_op.f('ix_execution_tasks_approval_request_id'))

    op.drop_table('execution_tasks')
    with op.batch_alter_table('diagnostic_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_evidence_cause_id'))

    op.drop_table('diagnostic_evidence')
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_results_plan_id'))

    op.drop_table('simulation_results')
    with op.batch_alter_table('diagnostic_causes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_causes_diagnosis_id'))

    op.drop_table('diagnostic_causes')
    with op.batch_alter_table('control_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_commands_plan_id'))
        batch_op.drop_index(batch_op.f('ix_control_commands_approval_request_id'))

    op.drop_table('control_commands')
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_invocations_task_id'))

    op.drop_table('tool_invocations')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_plan_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_task_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_results_event_id'))

    op.drop_table('diagnosis_results')
    with op.batch_alter_table('control_plan_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_plan_versions_plan_id'))

    op.drop_table('control_plan_versions')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_plan_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('telemetry_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_series_room_id'))

    op.drop_table('telemetry_series')
    with op.batch_alter_table('security_audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_event_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_entries_correlation_id'))

    op.drop_table('security_audit_entries')
    with op.batch_alter_table('event_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_reports_event_id'))

    op.drop_table('event_reports')
    with op.batch_alter_table('control_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_plans_event_id'))

    op.drop_table('control_plans')
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tasks_event_id'))

    op.drop_table('agent_tasks')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_room_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('room_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_events_room_id'))

    op.drop_table('room_events')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_room_id'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_room_id'))

    op.drop_table('devices')
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_events_room_id'))

    op.drop_table('anomaly_events')
    with op.batch_alter_table('safety_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_rules_rule_code'))

    op.drop_table('safety_rules')
    op.drop_table('cold_rooms')
    # ### end Alembic commands ###
